// Write your solution here!
This assignment does not work when I execute npm install, nor does it work with npm test...just an uknown options preset error and something related to Babel??
I dont know how to proceed...